---
deployment:
  tasks:
    - export DEPLOYPATH=/home/djucnxxj/public_html/
    - /bin/rsync -amv frontend/dist/ $DEPLOYPATH
    - export BACKENDPATH=/home/djucnxxj/tlc_backend/
    - /bin/rsync -amv --exclude='database.db' --exclude='__pycache__' --exclude='.pytest_cache' backend/ $BACKENDPATH
