---
deployment:
  tasks:
    - cp -rf frontend/dist/* /home/djucnxxj/public_html/consilindo.biz.id/tlc_yatz/
    - cp -rf backend/* /home/djucnxxj/tlc_backend/
    - touch /home/djucnxxj/tlc_backend/tmp/restart.txt
