---
deployment:
  tasks:
    - /bin/rsync -amv frontend/dist/ /home/djucnxxj/public_html/
    - /bin/rsync -amv --exclude='database.db' --exclude='__pycache__' --exclude='.pytest_cache' backend/ /home/djucnxxj/tlc_backend/
